### ISSUE TITLE
UserWarning: cannot import name '_C' from 'sam2' 

### ISSUE THREAD

**Issue by laisimiao** [yangchris11/samurai#62]
```
/home/xxx/PycharmProjects/samurai/sam2/sam2/sam2_video_predictor.py:961: UserWarning: cannot import name '_C' from 'sam2' (/home/xxx/PycharmProjects/samurai/sam2/sam2/__init__.py)

Skipping the post-processing step due to the error above. You can still use SAM 2 and it's OK to ignore the error above, although some post-processing functionality may be limited (which doesn't affect the results in most cases; see https://github.com/facebookresearch/sam2/blob/main/INSTALL.md).
```
What operations are included in the post-processing process? Why we can ignore the error above?

**Comment by zhyjiang** [comment]
This is an error in the original SAM2 lib. You may check this issue: https://github.com/facebookresearch/sam2/issues/25

**Comment by havinggood** [comment]
> 这是原始 SAM2 库中的错误。你可以检查这个问题： [facebookresearch/sam2#25](https://github.com/facebookresearch/sam2/issues/25)

I'm having the same problem with my torch is 2.3.1，cuda12.1，Run the solution in issue25：python setup.py build_ext --inplace Report an error：
CUDA_HOME environment variable is not set.  Please set it to your CUDA install root.

Failed to build the SAM 2 CUDA extension due to the error above.  You can still use SAM 2 and it's OK to ignore the error above, although some post-processing functionality may be limited (which doesn't affect the results in most cases;  (see https://github.com/facebookresearch/sam2/blob/main/INSTALL.md).

**Comment by yangchris11** [comment]
@havinggood Our code base did not modify any cuda-related code nor require any further version of torch. We recommend you to first set-up the original SAM 2 environment and run a quick test to ensure the enviroment is set up correctly.
