### ISSUE TITLE
Object Tracking Starting from a Specific Frame

### ISSUE THREAD

**Issue by maralbek** [yangchris11/samurai#81]
Hi,

Thank you for the amazing work and effort you've put into this project!

I have a question regarding object tracking: Is it possible to start tracking an object from a specific frame instead of the very first frame of the video? For instance, if my object of interest only becomes visible from frame 10 onward, how can I configure the system to start tracking from that frame?

I attempted to modify the starting frame manually, but encountered a KeyError.

**Comment by MlLearnerAkash** [comment]
I also do have some similar requirements.
Lets say some objects appears at n frame along with the other existing items.
How to start tracking this new item along with the existing ones?
@yangchris11 , can you please help on this.

**Comment by yangchris11** [comment]
@maralbek Since SAMURAI is directly adapt from the original SAM 2, you can refer to the lines to modify the `load_video_frames` to meet your requirement of tracking object from a specific frame.

https://github.com/yangchris11/samurai/blob/c38520be4406d0a064efc37c47e0e68d65ee0c61/sam2/sam2/sam2_video_predictor.py#L51-L59

**Comment by yangchris11** [comment]
@MlLearnerAkash The current SAMURAI is design for tracking one object at a time due to the current memory bank implementation. Different objects will require different memory from different set of frames therefore does not work with the existing SAM 2 pipeline on adding new object "in the middle" of the tracking process.

**Comment by MlLearnerAkash** [comment]
@yangchris11 
But, it is necessary and essential condition for for real-life scenarios.

Can you please guide us to incorporate this feature by ourselves?

Because debugging the whole codebase is cumbersome.

**Comment by yangchris11** [comment]
@MlLearnerAkash We suggest you take a look at https://github.com/IDEA-Research/Grounded-SAM-2 in the "Grounded-SAM-2 Video Object Tracking with Continuous ID (with Grounding DINO)" section to get some idea about the necessary changes you will need. 

Again, SAMURAI focus on visual object tracking and try to explore around how motion can help in the memory bank formation. The support/feature of tracking multiple instances in the "same pass" is not in our plan at this moment due to our bandwidth, thank you for your understanding.

**Comment by MlLearnerAkash** [comment]
Thanks @yangchris11 , thanks for your help. Appreciate it.
